First draft of ARCHITECTURE.md
linebender/xilem pull request #277
Opened 2024-05-06 13:40 UTC by giannissc

2024-05-06 13:49 UTC, waywardmonkeys requested changes
I'd suggest checking for other similar issues ... I just found them via visual scan, not intense search.

2024-05-06 13:49 UTC, waywardmonkeys commented on ARCHITECTURE.md
> +Xilem is a frameworks that aims to provide a performant and productive option for Rust GUI.
"framework"

2024-05-06 13:49 UTC, waywardmonkeys commented on ARCHITECTURE.md
> +This crates evolved from various experiments in the linebender community (Druid, masonry, idiopath, lasagna, crochet, etc)
"Linebender" (not sure about the others).

2024-05-06 13:49 UTC, waywardmonkeys commented on ARCHITECTURE.md
> +- **High Performance.** Lightweight state management, retained widget layer, massively parallel rendering backend (vello), fast startup time, small binary size
"Vello"

2024-05-06 13:49 UTC, waywardmonkeys commented on ARCHITECTURE.md
> +The most imporant construct at the reactive layer is the `View` trait. `View` implementations need to assign the associated  `State` and `Element` and implement `build()`, `rebuild()` and `message()`
"important"

2024-05-06 13:49 UTC, waywardmonkeys commented on ARCHITECTURE.md
> +The most imporant construct at the reactive layer is the `View` trait. `View` implementations need to assign the associated  `State` and `Element` and implement `build()`, `rebuild()` and `message()`
and there are 2 spaces between "associated" and "`State`"

2024-05-06 14:15 UTC, giannissc commented
I have created this a while ago and updated it a bit today. If its urgent to get into Xilem don't rely on me finding the time to finish it as I will  be packed until the end of the month..!

2024-05-07 13:51 UTC, waywardmonkeys approved these changes
Since this is just a step on a long road ... let's start it.

2024-05-07 16:39 UTC, giannissc commented
That's what I thought! Anything else you would like me to add before we merge? @PoignardAzur

2024-05-08 07:18 UTC, PoignardAzur commented
LGTM.

2024-05-08 09:11 UTC, merged