Remove bloom filter
linebender/xilem pull request #536
Opened 2024-08-24 16:26 UTC by PoignardAzur

The filter was only used for RouteFocusChanged which is about to be removed. Since it was a performance feature, we can remove it early.

2024-08-24 16:30 UTC, waywardmonkeys requested changes
You will be able to remove the `fnv` dependency from both The masonry Cargo.toml but also the workspace one and Cargo.lock

2024-08-24 22:13 UTC, PoignardAzur commented
Done.

2024-08-24 23:56 UTC, waywardmonkeys approved these changes
LGTM once the changes to the. Item example are removed.

2024-08-24 23:56 UTC, waywardmonkeys commented on xilem/examples/to_do_mvc.rs
> +    next_task2: String,
These changes to a xilem example seem unrelated and don’t belong in this PR.

2024-08-25 08:47 UTC, waywardmonkeys commented on xilem/examples/to_do_mvc.rs
> +    flex((first_line, input_box2, tasks))
You still have this bit in there...

2024-08-25 08:48 UTC, waywardmonkeys commented on xilem/examples/to_do_mvc.rs
> +    flex((first_line, input_box2, tasks))
You got it now.

2024-08-25 08:56 UTC, merged